[package]
name = "mexpress"
version = "0.1.1"
edition = "2018"

[lib]
name = "mexpress"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exmex = { git = "https://github.com/bertiqwerty/exmex.git", rev = "474f8f5" }
numpy = "0.14"

[dependencies.pyo3]
version = "0.14"
features = ["extension-module"]

[package.metadata.maturin]
python-source = "py"
