[project]
name = "mexpress"
dependencies = ["numpy"]
license = {"file" = "LICENSE" }
description = "Math parser and evaluator capable of computing gradients and Hessians."
repository = "https://github.com/bertiqwerty/mexpress"
readme = "README.md"

[build-system]
requires = ["maturin>=0.11,<0.12"]
build-backend = "maturin"

