name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests with test.pypi.org package
        run: |
          pip install pytest
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mexpress
          pytest py/test/test.py          
      - name: Run tests with PyPI package
        run: |
          pip install --ignore-installed mexpress
          pytest py/test/test.py
