name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: '3.12'
    - name: Run Pipeline
      run: |
        pip3 install uv
        uv sync --group dev
        uv run maturin develop
        uv run pytest test
        ruff check .
        ruff format --check .
