name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests with PyPI package
        run: |
          pip install pytest
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ mexpress
          pytest test/test.py
      - name: Run tests with PyPI package
        run: |
          pip install pytest mexpress
          pytest test/test.py
