name: Test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run Pipeline
      run: |
        python3 -m venv .venv
        . .venv/bin/activate
        pip3 install -r requirements-dev.txt
        maturin develop
        pytest test
        ruff check .
